# Generated by Django 5.0.4 on 2024-05-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vendor_address_alter_vendor_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact_details',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
