# Generated by Django 5.0.4 on 2024-05-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vendor_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(max_length=50),
        ),
    ]
